# Generated by Django 4.2 on 2023-11-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextID',
            fields=[
                ('uuid', models.UUIDField(default='uuid.uuid4', editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'TextID_table',
            },
        ),
    ]
