# Generated by Django 4.2 on 2023-11-15 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_alter_textid_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='textid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
