version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: git_examples
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  client_app:
    build:
      context: ./client_app
      dockerfile: Dockerfile
    command: python client_app/app/client_app.py
    depends_on:
      - web
